name: Deploy Lambda

on:
  push:
    branches:
      - main
    paths:
      - "lambda-upload/**" # Only runs if you change code inside the lambda folder

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: |
          cd lambda-upload
          npm install

      - name: Zip Lambda
        run: |
          cd lambda-upload
          zip -r ../lambda.zip .

      - name: Deploy to AWS Lambda
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_SECRET_KEY }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: asciente-upload-handler
          zip_file: lambda.zip
